.PHONY: build up start stop down status centos

build:
	docker-compose build

up:
	docker-compose up -d

start:
	docker-compose start

stop:
	docker-compose stop

down:
	docker-compose down

status:
	docker-compose ps

centos:
	docker-compose exec centos /bin/bash